/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.cine.salas.Sala;
import backend.arbol.Tree;
import backend.cine.peliculas.Pelicula;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USUARIO ASUS
 */
public class SalaCine extends javax.swing.JFrame {

    private int butaca, anterior;
    private Sala sala;
    private List<Sala> salas;
    
    public SalaCine(Sala sala, List<Sala> salas) throws IOException {
        anterior=0;
        butaca = 0;
        this.sala = sala;
        this.setUndecorated(true);
        initComponents();
        jButton2.setEnabled(false);
        this.setLocationRelativeTo(null);
        jTextField1.setEditable(false);
        
        this.comprobarAsientos(sala);
    }
    
    public SalaCine(Sala sala, int previous, List<Sala> salas) throws IOException {
        anterior=previous;
        this.salas = salas;
        butaca = 0;
        this.sala = sala;
        this.setUndecorated(true);
        initComponents();
        jButton2.setEnabled(false);
        this.setLocationRelativeTo(null);
        jTextField1.setEditable(false);
        
        this.comprobarAsientos(sala);
    }

    
    public void comprobarAsientos(Sala sala){
        Tree disponibilidad = sala.getAsientos();
        for(int i=1;i<=12;i++){
            if(i==1 && disponibilidad.disponible(i)==false){
                jLabelButaca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca1.setEnabled(false);
            }
            if(i==2 && disponibilidad.disponible(i)==false){
                jLabelButaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca2.setEnabled(false);
            }
            if(i==3 && disponibilidad.disponible(i)==false){
                jLabelButaca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca3.setEnabled(false);
            }
            if(i==4 && disponibilidad.disponible(i)==false){
                jLabelButaca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca4.setEnabled(false);
            }
            if(i==5 && disponibilidad.disponible(i)==false){
                jLabelButaca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca5.setEnabled(false);
            }
            if(i==6 && disponibilidad.disponible(i)==false){
                jLabelButaca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca6.setEnabled(false);
            }
            if(i==7 && disponibilidad.disponible(i)==false){
                jLabelButaca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca7.setEnabled(false);
            }
            if(i==8 && disponibilidad.disponible(i)==false){
                jLabelButaca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca8.setEnabled(false);
            }
            if(i==9 && disponibilidad.disponible(i)==false){
                jLabelButaca9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca9.setEnabled(false);
            }
            if(i==10 && disponibilidad.disponible(i)==false){
                jLabelButaca10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca10.setEnabled(false);
            }
            if(i==11 && disponibilidad.disponible(i)==false){
                jLabelButaca11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca11.setEnabled(false);
            }
            if(i==12 && disponibilidad.disponible(i)==false){
                jLabelButaca12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roja.png")));
                Butaca12.setEnabled(false);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelButaca12 = new javax.swing.JLabel();
        jLabelButaca11 = new javax.swing.JLabel();
        jLabelButaca10 = new javax.swing.JLabel();
        jLabelButaca9 = new javax.swing.JLabel();
        jLabelButaca8 = new javax.swing.JLabel();
        jLabelButaca7 = new javax.swing.JLabel();
        jLabelButaca6 = new javax.swing.JLabel();
        jLabelButaca5 = new javax.swing.JLabel();
        jLabelButaca4 = new javax.swing.JLabel();
        jLabelButaca3 = new javax.swing.JLabel();
        jLabelButaca2 = new javax.swing.JLabel();
        jLabelButaca1 = new javax.swing.JLabel();
        jLabelButacas = new javax.swing.JLabel();
        Butaca12 = new javax.swing.JButton();
        Butaca11 = new javax.swing.JButton();
        Butaca10 = new javax.swing.JButton();
        Butaca9 = new javax.swing.JButton();
        Butaca8 = new javax.swing.JButton();
        Butaca7 = new javax.swing.JButton();
        Butaca6 = new javax.swing.JButton();
        Butaca5 = new javax.swing.JButton();
        Butaca4 = new javax.swing.JButton();
        Butaca3 = new javax.swing.JButton();
        Butaca2 = new javax.swing.JButton();
        Butaca1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameSalaCine"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelButaca12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        jLabelButaca12.setText("jLabel1");
        getContentPane().add(jLabelButaca12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 50, 50));

        jLabelButaca11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        jLabelButaca11.setText("jLabel2");
        getContentPane().add(jLabelButaca11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, -1));

        jLabelButaca10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabelButaca9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabelButaca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 50, 50));

        jLabelButaca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabelButaca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabelButaca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabelButaca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 50, 50));

        jLabelButaca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabelButaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabelButaca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gris.png"))); // NOI18N
        getContentPane().add(jLabelButaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabelButacas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosala.png"))); // NOI18N
        getContentPane().add(jLabelButacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        Butaca12.setText("jButton1");
        Butaca12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca12ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 50, 70));

        Butaca11.setText("jButton1");
        Butaca11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca11ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, 70));

        Butaca10.setText("jButton1");
        Butaca10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca10ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 50, 70));

        Butaca9.setText("jButton1");
        Butaca9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca9ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 50, 70));

        Butaca8.setText("jButton1");
        Butaca8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca8ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 50, 70));

        Butaca7.setText("jButton1");
        Butaca7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca7ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 50, 70));

        Butaca6.setText("jButton1");
        Butaca6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca6ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 50, 70));

        Butaca5.setText("jButton1");
        Butaca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca5ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 50, 70));

        Butaca4.setText("jButton1");
        Butaca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca4ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 50, 60));

        Butaca3.setText("jButton1");
        Butaca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca3ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, 70));

        Butaca2.setText("jButton1");
        Butaca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca2ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 50, 70));

        Butaca1.setText("jButton1");
        Butaca1.setName("Butaca1"); // NOI18N
        Butaca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butaca1ActionPerformed(evt);
            }
        });
        getContentPane().add(Butaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, 70));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("SELECCIONA UNA BUTACA");
        jTextField1.setName(""); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 290, 80));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CONTINUAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 140, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoF.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 472));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Butaca11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca11ActionPerformed
        butaca=11;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 11");
    }//GEN-LAST:event_Butaca11ActionPerformed

    private void Butaca12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca12ActionPerformed
        butaca=12;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 12");
    }//GEN-LAST:event_Butaca12ActionPerformed

    private void Butaca9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca9ActionPerformed
        butaca=9;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 9");
    }//GEN-LAST:event_Butaca9ActionPerformed

    private void Butaca10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca10ActionPerformed
        butaca=10;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 10");
    }//GEN-LAST:event_Butaca10ActionPerformed

    private void Butaca8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca8ActionPerformed
        butaca=8;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 8");
    }//GEN-LAST:event_Butaca8ActionPerformed

    private void Butaca7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca7ActionPerformed
        butaca=7;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 7");
    }//GEN-LAST:event_Butaca7ActionPerformed

    private void Butaca6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca6ActionPerformed
        butaca=6;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 6"); 
    }//GEN-LAST:event_Butaca6ActionPerformed

    private void Butaca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca5ActionPerformed
       butaca=5;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 5");
    }//GEN-LAST:event_Butaca5ActionPerformed

    private void Butaca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca4ActionPerformed
        butaca=4;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 4");
    }//GEN-LAST:event_Butaca4ActionPerformed

    private void Butaca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca3ActionPerformed
       butaca=3;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 3");
    }//GEN-LAST:event_Butaca3ActionPerformed

    private void Butaca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca2ActionPerformed
        butaca=2;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 2");
    }//GEN-LAST:event_Butaca2ActionPerformed

    private void Butaca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butaca1ActionPerformed
        butaca=1;
        jButton2.setEnabled(true);
        jTextField1.setText("HAS SELECCIONADO LA BUTACA 1");
    }//GEN-LAST:event_Butaca1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Catalogo cat;
        try {
            cat = new Catalogo(anterior);
            cat.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SalaCine.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Formulario form;
        try {
            form = new Formulario(butaca, sala, anterior, salas);
            form.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SalaCine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butaca1;
    private javax.swing.JButton Butaca10;
    private javax.swing.JButton Butaca11;
    private javax.swing.JButton Butaca12;
    private javax.swing.JButton Butaca2;
    private javax.swing.JButton Butaca3;
    private javax.swing.JButton Butaca4;
    private javax.swing.JButton Butaca5;
    private javax.swing.JButton Butaca6;
    private javax.swing.JButton Butaca7;
    private javax.swing.JButton Butaca8;
    private javax.swing.JButton Butaca9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelButaca1;
    private javax.swing.JLabel jLabelButaca10;
    private javax.swing.JLabel jLabelButaca11;
    private javax.swing.JLabel jLabelButaca12;
    private javax.swing.JLabel jLabelButaca2;
    private javax.swing.JLabel jLabelButaca3;
    private javax.swing.JLabel jLabelButaca4;
    private javax.swing.JLabel jLabelButaca5;
    private javax.swing.JLabel jLabelButaca6;
    private javax.swing.JLabel jLabelButaca7;
    private javax.swing.JLabel jLabelButaca8;
    private javax.swing.JLabel jLabelButaca9;
    private javax.swing.JLabel jLabelButacas;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
